version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: wakeup-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: q1w2e3
      MYSQL_DATABASE: wakeup
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
